// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'API_KEY_WEB',
    appId: 'APP_ID_WEB',
    messagingSenderId: 'MESSAGING_SENDER_ID_WEB',
    projectId: 'PROJECT_ID_WEB',
    authDomain: 'AUTH_DOMAIN_WEB',
    databaseURL: 'DATABASE_URL_WEB',
    storageBucket: 'STORAGE_BUCKET_WEB',
    measurementId: 'MEASUREMENT_ID_WEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'API_KEY_ANDROID',
    appId: 'APP_ID_ANDROID',
    messagingSenderId: 'MESSAGING_SENDER_ID_ANDROID',
    projectId: 'PROJECT_ID_ANDROID',
    databaseURL: 'DATABASE_URL_ANDROID',
    storageBucket: 'STORAGE_BUCKET_ANDROID',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'API_KEY_IOS',
    appId: 'APP_ID_IOS',
    messagingSenderId: 'MESSAGING_SENDER_ID_IOS',
    projectId: 'PROJECT_ID_IOS',
    databaseURL: 'DATABASE_URL_IOS',
    storageBucket: 'STORAGE_BUCKET_IOS',
    iosClientId: 'IOS_CLIENT_ID_IOS',
    iosBundleId: 'IOS_BUNDLE_ID_IOS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'API_KEY_MACOS',
    appId: 'APP_ID_MACOS',
    messagingSenderId: 'MESSAGING_SENDER_ID_MACOS',
    projectId: 'PROJECT_ID_MACOS',
    databaseURL: 'DATABASE_URL_MACOS',
    storageBucket: 'STORAGE_BUCKET_MACOS',
    iosClientId: 'IOS_CLIENT_ID_MACOS',
    iosBundleId: 'IOS_BUNDLE_ID_MACOS',
  );
}
